---
name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  ci:
    name: Run ${{ matrix.target }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target: [lint, test]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup caching
        uses: Swatinem/rust-cache@v2

      - name: "Set environment variables used by toolchain"
        shell: bash
        run: |
          echo CARGO_TERM_COLOR=always >> $GITHUB_ENV
          echo CARGO_INCREMENTAL=0 >> $GITHUB_ENV
          echo RUST_BACKTRACE=1 >> $GITHUB_ENV

      - name: "Install rust toolchain"
        run: rustup show

      - name: Install assembler
        if: matrix.target == 'test'
        run: sudo apt-get install xa65 -y
  
      - name: Run ${{ matrix.target }}
        run: make ${{ matrix.target }}
